- Applied z1807...z1809 updates.
Signed-off-by: TheLuda <theluda@getmangos.com>

diff --git a/mysql_import b/mysql_import
--- a/mysql_import
+++ b/mysql_import
@@ -3,29 +3,36 @@
 # This script will import the contents of the sql/ directory to the MySQL database.
 #
 
-. ./mysql_info
+# - Include common libraries and settings ------------------------------------
+source "libui"
+source "mysql_info"
+
+# - Prepare required variables -----------------------------------------------
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+TMP_FOLDER=${TMPDIR-/tmp}
+# ----------------------------------------------------------------------------
 
 # Table prefix
 PFX=
 
 function import ()
 {
-    db=$PFX`sed -ne '/^--.*Database: /{' -e 's/.*Database: //' -e 'p' -e '}' $1`
-    echo -n "Importing $1 into $db ..."
+    db=${PFX}`sed -ne '/^--.*Database: /{' -e 's/.*Database: //' -e 'p' -e '}' $1`
+    echo -n "Importing $1 into ${db} ..."
     # Check if database exists
-    err=`echo "quit" | mysql$OPTS $db 2>&1`
+    err=`echo "quit" | mysql${OPTS} ${db} 2>&1`
     if [ $? != 0 ]; then
-        if echo "$err" | grep -q "Access denied"; then
-            echo -e "\nDATABASE $db EXISTS BUT USER $USER DOES NOT HAVE ACCESS TO IT, ABORTING"
+        if echo "${err}" | grep -q "Access denied"; then
+            echo -e "\nDATABASE ${db} EXISTS BUT USER ${USER} DOES NOT HAVE ACCESS TO IT, ABORTING"
             exit
         fi
-        echo -n "[creating $db]"
-        if ! echo "CREATE DATABASE $db;" | mysql$OPTS 2>/dev/null ; then
-            echo -e "\nDATABASE $db DOES NOT EXIST AND I FAILED TO CREATE IT, ABORTING"
+        echo -n "[creating ${db}]"
+        if ! echo "CREATE DATABASE ${db};" | mysql${OPTS} 2>/dev/null ; then
+            echo -e "\nDATABASE ${db} DOES NOT EXIST AND I FAILED TO CREATE IT, ABORTING"
             exit
         fi
     fi
-    mysql$OPTS $db <$1
+    mysql${OPTS} ${db} <$1
     echo " done"
 }
 
